feat: creating function to generate qr code in sdk itau
AstrotechLabs/itau-sdk pull request #1
Opened 2024-01-06 00:41 UTC by PietroCoelho

2024-01-08 18:33 UTC, MoisesK requested changes

2024-01-08 18:33 UTC, MoisesK commented on docker-compose.yml
> +  melhorenvio-network:
@PietroCoelho ou ajusta esse docker-compose para o itaú-sdk ou remove o arquivo!

2024-01-08 18:33 UTC, MoisesK commented on src/ImmediateQRCode/IssueImmediateQRCode/Dto/Debtor.php
> +            "cpf" => preg_replace('/[^0-9]/', '', $this->cpf),
@PietroCoelho Realiza esta limpeza no ato do construtor, pois neste caso do método `toArray()` você daria um return [
    'nome' => $this->name,
    'cpf' => $this->cpf,
    'cnpj' => $this->cnpj
];

2024-01-08 18:33 UTC, MoisesK commented on src/ImmediateQRCode/IssueImmediateQRCode/Dto/InputData.php
> +        return array_filter([
@PietroCoelho aqui da mesma forma, dê um return em um array com a estrutura específica, não há necessidade de um `array_filter()`

2024-01-08 18:33 UTC, MoisesK commented on src/ImmediateQRCode/IssueImmediateQRCode/Dto/Value.php
> +            "modalidadeAlteracao" => $this->changeModality
@PietroCoelho Porque este campo está com a key em BR?

2024-01-08 18:33 UTC, MoisesK commented on src/ItauGateway.php
> +    public function createImmediateQRCode(InputData $inputData)
@PietroCoelho normalmente nestes métodos que vamos bater lá na api e criar a cobrança, chamamos de `createCharge()` ou `createPixCharge()` Adota uma destas duas nomenclaturas para manter o padrão de nossos sdk de pagamento.

2024-01-08 20:09 UTC, italo-at commented on tests/Integration/ImmediateQRCode/IssueImmediateQRCodeTest.php
> +    public function testMustReturnTheInformationAfterIssuingTheQrCodeWithTheMinimumNumberOfFieldsFilledIn()
Qual é a informação em 'the information'? Acho que da forma que está escrito fica pedindo esclarecimento. Sugiro mudar para algo como testReceivesQrCodeInfoWhenIssuingQrCodeWithMinimumFields

2024-01-08 20:14 UTC, italo-at commented on src/ImmediateQRCode/IssueImmediateQRCode/IssueImmediateQRCode.php
> +    public function issued(InputData $input): OutputData
Troca 'issued' por 'issue', que é uma ação. (Issued faz parecer que está acessando uma propriedade que já foi issued, quando na verdade se está executando uma ação)

2024-01-08 20:20 UTC, italo-at commented on src/ImmediateQRCode/IssueImmediateQRCode/IssueImmediateQRCode.php
> +        return new OutputData(
Eu acho que a leitura do código é mais simples quando o return está dentro do try. Mas isso é apenas uma opinião, não uma solicitação de mudança. Comentando só pro caso de fazer sentido pra ti.

2024-01-08 20:26 UTC, italo-at commented on tests/Integration/ImmediateQRCode/IssueImmediateQRCodeTest.php
> +    public function testReturnAnErrorWhenThePixKeyIsIncorrect()
Só uma questão de inglês, os nomes de testes são mais descritivos quando estão no presente. Pra isso eu adicionaria um s no fim de Return (ou mudaria ele pra Receives ou Gets, já que testa o que é recebido da chamada)

2024-01-08 20:28 UTC, italo-at commented on tests/Integration/ImmediateQRCode/IssueImmediateQRCodeTest.php
> +    use HttpClientMock;
Os métodos dessa trait são chamados?

2024-01-08 20:52 UTC, italo-at approved these changes

2024-01-08 20:53 UTC, italo-at approved these changes

2024-01-09 13:08 UTC, MoisesK approved these changes

2024-01-09 13:12 UTC, merged